sudo: required
language: generic
services:
  - docker

install:
  - docker run -itd --name build --net="host"
    -v $(pwd):/catkin_ws/src/repo
    ros:indigo-perception
    
before_script:
  - gem install coveralls-lcov
  - docker exec build bash -c 'apt-get update && apt-get install -y ros-indigo-desktop-full cmake libeigen3-dev libopenblas-dev  liblapack-dev libarpack* libarmadillo*'
  - docker exec build bash -c 'source /opt/ros/indigo/setup.bash'

script:
  - docker exec build bash -c 'source /opt/ros/indigo/setup.bash && cd /catkin_ws && catkin_make'
